---
title: "SOC 301: Methods of Social Research"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: cosmo
---

## Course Description 

As a social science, sociology generally follows the scientific method in an effort to describe and interpret the social world. This course considers the logic and tools sociologists use to study social problems in a scientific way. Without those tools, the discussion of social problems can deteriorate into expressions of opinions and observations based on personal experience. 

## Course Objectives

By the end of the course students will be able to: 

1. Describe the basic logic behind scientific research
2. Explain the basic steps and procedures involved in empirical social research
3. Demonstrate knowledge of and ability to execute conceptualization and measurement, research design, and selected research methods to carry out research projects
4. Read, understand, and critically evaluate social data, including in multivariate studies and tables
5. Carry out library research and Internet searches for research topics
6. Explain the role of research in sociology
7. Use the basic vocabulary of research in sociology
8. Demonstrate knowledge of major sociological methods such as survey research, qualitative interviewing, ethnography, secondary data analysis, analysis of existing statistics, systematic social observation, and experiments
9. Differentiate research articles from other forms of scholarship
10. Identify the research methods used in a research study 
11. Identify biased and poorly done research and explain its shortcomings

## Required Textbook

Liahna Gordon, <em>Real Research: Research Methods Sociology Students Can Use</em>



